// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/preregister": {
    params: {};
  };
  "/results": {
    params: {};
  };
  "/admin": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/preregister" | "/results" | "/admin";
  };
  "./pages/index.tsx": {
    id: "pages/index";
    page: "/";
  };
  "./pages/preregister.tsx": {
    id: "pages/preregister";
    page: "/preregister";
  };
  "./pages/results.tsx": {
    id: "pages/results";
    page: "/results";
  };
  "./pages/admin.tsx": {
    id: "pages/admin";
    page: "/admin";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "pages/index": typeof import("./src/./pages/index.tsx");
  "pages/preregister": typeof import("./src/./pages/preregister.tsx");
  "pages/results": typeof import("./src/./pages/results.tsx");
  "pages/admin": typeof import("./src/./pages/admin.tsx");
};